# Generated by Django 4.1.4 on 2022-12-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_patrticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='patrticipants',
            new_name='participants',
        ),
    ]
